### ISSUE TITLE
Suggesting Instructions on Read Me

### ISSUE THREAD

**Issue by GioPanda96** [RedBrumbler/CustomPillowsQuest#3]
I suggest updating the read me file with some instructions, mainly where to upload the pictures, the supported formats, the dimensions or ratio height/width, how to access the directory, if you can upload more than one picture etc.

**Comment by RedBrumbler** [comment]
If you could go over them and make sure they are clear, that would be great :p

**Comment by GioPanda96** [comment]
Perfect! Thank you!
