### ISSUE TITLE
Does not load in after failing or passing a song

### ISSUE THREAD

**Issue by BallinAssCat** [RedBrumbler/CustomPillowsQuest#4]
I am unsure on why this happens but the glitch works every time for me

**Comment by BallinAssCat** [comment]
here's a link to a google drive with a video of this [https://drive.google.com/file/d/1NpmHML0f_gkx7LBYOtFo5Jihnru1Xk6N/view?usp=sharing](url)

**Comment by RedBrumbler** [comment]
I've actually already fixed this, just not released it yet 😬

**Comment by BallinAssCat** [comment]
lol

**Comment by BallinAssCat** [comment]
when will that be realised?
